name: Update AWS Service List
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  updateAWSServiceList:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update AWS Service List in us-east-1
        run: >
          i=`aws iam generate-service-last-accessed-details --arn arn:aws:iam::aws:policy/AdministratorAccess --output text`
          && sleep 1
          && aws iam get-service-last-accessed-details --job-id $i --max-items 1000
          | jq '.ServicesLastAccessed
          | sort_by(.ServiceName)
          | map({ServiceName: .ServiceName})'
          > us-east-1.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update AWS Service List
          title: Update AWS Service List
          body: Update AWS Service List
          branch: update
